name: friends
recipe: drupal7
config:
  php: '8.0'
  webroot: .
  drush: '8.4.12'
services:
  node:
    type: 'node:8'
    globals:
      gulp-cli: latest
tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
